image: python:3.8-buster

stages:
  - dist
  - test

sdist_whl:
  stage: dist
  before_script:
    - pip install poetry
  script:
    - poetry build

install:
  stage: test
  dependencies:
    - sdist_whl
  script:
    - poetry install

test:
  stage: test
  dependencies:
    - install
  script:
    - poetry run pytest

