image: python:3.8-buster

stages:
  - test
  - install

build_test:
  stage: test 
  before_script:
    - pip install poetry
  script:
    - poetry install
    - poetry run pytest
    - poetry build
    - mv dist/* .
  artifacts:
    paths:
      - '*tar.gz'
      - '*whl'

tar_whl:
  stage: install
  dependencies:
    - build_test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install ./*tar.gz
    - pip install ./*whl
